### ISSUE TITLE
Looking for (co-)maintainer

### ISSUE THREAD

**Issue by mristin** [mristin/opinionated-commit-message#112]
Hi @statuscake-machine, @1david5 and @johnboyes,
I fired up WebStorm today, tried to re-compile the project, and fix #110  and #28. The number of dependency warnings and errors was just overwhelming. This is all too much for me, as I reserved only one-two hours for these issues today, and that is now up.

Would you perhaps be interested to help me co-maintain the package or take over the maintenance altogether?

**Comment by johnboyes** [comment]
Hi @mristin, I'd be keen to help but unfortunately I'm already in a similar position to you maintaining a few open-source projects, and I'm not proficient in TypeScript or JavaScript unfortunately.  It's a very valuable project so I hope you are able to keep it going and that you succeed in finding some co-maintainers 🤞🏻

**Comment by Fryuni** [comment]
Hey @mristin, we at @croct-tech use this action for all our repos and currently already maintain our own fork where we tested things before contributing back in the past.
We could probably help maintain this action.

If you would prefer to not have a company involved I personally can help with maintenance in my free time :)

**Comment by Fryuni** [comment]
I just opened a #120 updating all the dependencies (many had security advisories) and I'll have a look at #110 and #28 to see if I can get them working.

**Comment by mristin** [comment]
Thanks, @Fryuni! If you are OK with me merging pull requests with a little bit of delay (usually 2-3 days), we can just keep the workflow as it is.

Just ping me whenever you feel like a new patch/minor/major version is to be released (*e.g.*, by creating an issue or contacting me *via* LinkedIn).

**Comment by mristin** [comment]
I'll close the issue for now as it seems that there are enough updates thanks to @croct-tech and @fryuni :-)
