### ISSUE TITLE
Upgrade to node16

### ISSUE THREAD

**Issue by Schmiedwerk** [mristin/opinionated-commit-message#125]
Running your (great!) action leads to the following warning:

The following actions uses node12 which is deprecated and will be forced to run on node16: mristin/opinionated-commit-message@v3.0.1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by mristin** [comment]
@Schmiedwerk thanks for the report!

I'm swamped with work tasks till Jan 2024. @Fryuni would you mind having a look?

**Comment by Fryuni** [comment]
Sure, I'll send the upgrade and any required fix before new year.

**Comment by mristin** [comment]
@Fryuni @Schmiedwerk What version should be released? A patch version?

**Comment by Fryuni** [comment]
I think a patch is enough. This doesn't break any existing workflow

**Comment by mristin** [comment]
I finally decided to release a minor version, 3.1.0, as there were quite some enhancements.

Thanks again, @Fryuni !
