### ISSUE TITLE
Check for weird unicode in the message

### ISSUE THREAD

**Issue by faern** [mristin/opinionated-commit-message#129]
Hi. I was looking around for a github actions workflow to sanity check our commit messages. This looks really promising! But it does not solve one of our issues: Weird unicode stuff ending up in commit messages. I guess this is mostly due to some git GUIs and/or locale settings?

Most commonly strange newlines. I currently have a commit in `main` that I would have liked to catch that has content similar to this (as rendered by the terminal):
```
Add this new cool feature whatever<U+2028>

Body of commit
```

`U+2028` is a special line separator character. I don't think anyone wants them in their commit message history. But this action does not mark it as an error.

**Comment by mristin** [comment]
Hi Linus,
Thanks for raising the issue! I am currently too busy, but feel free to submit a pull request.

**Comment by faern** [comment]
I'll see if I have the time and knowledge to contribute. But before I do, what do you think is a reasonable way of solving it?

Should I look specifically for `U+2028` and forbid that? Denying everything that is non-ascii makes no sense, lots of people probably legitimately want to use that.

**Comment by mristin** [comment]
@faern this is the first time I see such a problem, so forbidding that character seems reasonable to me. I wouldn't forbid anything else.

@Fryuni any thoughts?

**Comment by faern** [comment]
For now I solved this in our repository by using the `gsactions/commit-message-checker@v2` action instead. I just wanted to post this here. If this seems to work well enough, I might not be motivated to patch this action.

```
- name: Check for unicode whitespaces
  uses: gsactions/commit-message-checker@v2
  with:
    # Pattern matches strings *not* containing weird unicode whitespace/separator characters
    # [^\p{Z}] = All non-whitespace characters (the u-flag is needed to enable \p{Z})
    # [ \t\n] = Allowed whitespace characters, these are OK in commit messages
    pattern: '^([^\p{Z}]|[ \t\n])+$'
    flags: 'u'
    error: 'Detected unicode whitespace character in commit message.'
    checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
    accessToken: ${{ secrets.GITHUB_TOKEN }} # only required if checkAllCommitMessages is true

```

**Comment by mristin** [comment]
Thanks, @faern !

I'll close the issue for now -- please re-open if your proposed solution does not work.
