### ISSUE TITLE
Accept body lines with 72 characters

### ISSUE THREAD

**Issue by krahlro-sick** [mristin/opinionated-commit-message#26]
[This check](https://github.com/mristin/doctest-csharp/runs/844399744#step:3:7) failed with the error message *The line 3 of the message (line 1 of the body) exceeds the limit of 72 characters.*  But the commit message has exactly 72 characters:

```
This patch fixes a typo in the readme file where this project was called
dead-csharp instead of doctest-csharp.
123456789012345678901234567890123456789012345678901234567890123456789012
```

The [code](https://github.com/mristin/opinionated-commit-message/blob/master/src/inspection.ts#L95) looks correct at first glance, but maybe the newline is counted as part of the line?  In this case, the subject check might be off by one too.

**Comment by mristin** [comment]
Hi @krahlro-sick ,
I created the corresponding unit test (see https://github.com/mristin/opinionated-commit-message/pull/34). However, I am not able to reproduce the error. Could you please verify that you did not have trailing white-space in your message?

**Comment by mristin** [comment]
I'll include the length of the invalid line in the error message to at least provide the user with the hint.

**Comment by krahlro-sick** [comment]
I'll have a look at it.  Maybe `\r\n` vs `\n`?

**Comment by krahlro-sick** [comment]
I amended the commit on my local branch and could not see any trailing whitespace.

**Comment by krahlro-sick** [comment]
[Here](https://github.com/admin-shell-io/aasx-package-explorer/pull/88/checks?check_run_id=853222918#step:3:7) is another example where I triple-checked that there is no trailing whitespace.

**Comment by mristin** [comment]
It turns out Github adds carriage returns to the body of the pull request. The pull request #46 fixes this issue.
