### ISSUE TITLE
One line commit messages should not be rejected

### ISSUE THREAD

**Issue by johnboyes** [mristin/opinionated-commit-message#55]
One line commit messages are currently rejected with the message:

`Expected at least three lines (subject, empty, body), but got: 1`

Chris Beams's [guidelines](https://chris.beams.io/posts/git-commit/#separate) say that one line messages are just fine, however:
> not every commit requires both a subject and a body. Sometimes a single line is fine, especially when the change is so simple that no further context is necessary.

**Comment by mristin** [comment]
Hi @johnboyes ,
Thanks for pointing that out! I'll add an additional input (allow-one-liner).

So far, enforcing a body proved to provoke people to write more informative messages, so I didn't even think about allowing one-liners.

**Comment by johnboyes** [comment]
Sounds good, thanks @mristin.  I'd propose allowing one liners as the default (as the guidelines say they are allowed), and adding a flag to optionally disallow them?

**Comment by mristin** [comment]
@johnboyes I added the feature and pushed the minor version to 2.1.0.

>  I'd propose allowing one liners as the default (as the guidelines say they are allowed), and adding a flag to optionally disallow them?

The action is already used in quite a few pipelines, so I left it as an optional flag (we actually want to disallow one-liners in those projects).

**Comment by johnboyes** [comment]
No problem, @mristin, and thanks for the quick turnaround 👍 

Once you have published the 2.1.0 release I'll give it a whirl 😎

**Comment by mristin** [comment]
@johnboyes the release should be up now.

**Comment by johnboyes** [comment]
Thanks @mristin, have updated my client repo to use it and have tested it - all working well.
